### ISSUE TITLE
Possible Missing Code

### ISSUE THREAD

**Issue by renxinyang** [DirtyHarryLYL/SymNet#3]
Dear authors,

After following the instructions and successfully running "python run_symnet.py --network fc_obj --name UT_obj_lr1e-3 --data UT --epoch 300 --batchnorm --lr 1e-3", I encountered the following error when running "python test_obj.py --network fc_obj --name UT_obj_lr1e-3 --data UT --epoch 140 --batchnorm"---

Traceback (most recent call last):
  File "E:/SymNet-master/test_obj.py", line 140, in <module>
    main()
  File "E:/SymNet-master/test_obj.py", line 41, in main
    sw.trainval_model(sess)
  File "E:/SymNet-master/test_obj.py", line 112, in trainval_model
    pred = self.network.test_step(sess, batch, prob_op, no_postprocess=True)
TypeError: test_step() got an unexpected keyword argument 'no_postprocess'

Process finished with exit code 1

I took a look at the test_step() function inside base_network.py, and it seems like this no_postprocess parameter should be there but was forgotten? It would be great if the authors could look into this issue. Thanks!

**Comment by silicx** [comment]
Thanks for using! This error is due to some missing code in "test_obj.py". The corresponding files have been fixed and updated in the latest commit.
