### ISSUE TITLE
Why train with pre-computed features?

### ISSUE THREAD

**Issue by vkhoi** [DirtyHarryLYL/SymNet#6]
Thanks for the great work and for making your code accessible. I have one question: can you explain why did you train with precomputed features? Why don't you fix the feature extractor and allow for image augmentation during training?

I understand that using precomputed features allows for faster training and exploration, but then you lose the benefits that image augmentation provides. I also see that you have new results on MIT-States (GCZSL setting) which is much better than what you reported in your paper (improve from 3.0 Top-1 AUC to 4.5). Did you allow for image augmentation to obtain these new results on MIT-States? If not, what has been changed to obtain these new results?

Thank you!

**Comment by silicx** [comment]
Hi, 

For fair comparison to other methods, we use the same pretrained feature extractor provided by PyTorch model zoo, which is not compatible with our TensorFlow model. So we cannot train directly from image. We are currently working on migrating to PyTorch to enhance compatibility and enable data augmentation. The MIT-States GCZSL results are improved by carefully tuning the hyperparameters and did not use augmentation.

**Comment by vkhoi** [comment]
Thanks for the answer!
