### ISSUE TITLE
复现过程中，测试阶段代码跑不通

### ISSUE THREAD

**Issue by 1173161983** [DirtyHarryLYL/SymNet#9]
你好，我正在尝试复现您的工作，但是在测试阶段代码好像有问题：
错误如下：
![image](https://user-images.githubusercontent.com/41355745/140971577-ce9d69d1-1e7f-4756-9cf7-a79b323b12cf.png)

请问这是什么原因造成的呢？

**Comment by 1173161983** [comment]
在模型训练第一阶段：Training a object classifier，调用network fc_obj 在base_network.py中调用了test_attr_id以及test_obj_id,但在fc_obj.py中没有相关变量的定义

**Comment by silicx** [comment]
Thanks! It is fixed in the [latest commit](https://github.com/DirtyHarryLYL/SymNet/commit/e01d7303c8bf76fda2a0e7aa3d641114aac678cc).
